version: "3.8"

services:
  ### 📌 MySQL Database
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=ameya123
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=ameya
      - MYSQL_PASSWORD=ameya123
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app_network

  ### 📌 Elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=ameya123
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - app_network

  ### 📌 Redis with Password
  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    command: redis-server --requirepass ameya123
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
  
volumes:
  dbdata:
    driver: local
  esdata:
    driver: local
  redisdata:
    driver: local
