version: "3.8"

services:

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app_network
  
  app:
    image: laravelblog:latest
    container_name: laravel_app
    restart: unless-stopped
    environment:
      - APP_ENV=production
      - APP_KEY=base64:famGtvBDKbelkGus5JPvc3TKdzibEEy1lho/xjpT6xU=
      - APP_DEBUG=false
      - APP_URL=http://localhost:8000
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=root
      - DB_PASSWORD=ameya123
      - REDIS_CLIENT=predis
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=ameya123
      - QUEUE_CONNECTION=redis
      - CACHE_STORE=redis
      - CACHE_DRIVER=array
      - ELASTICSEARCH_HOST=http://elasticsearch:9200
      - ELASTICSEARCH_USER=elastic
      - ELASTICSEARCH_PASSWORD=ameya123
      - MAIL_MAILER=smtp
      - MAIL_HOST=sandbox.smtp.mailtrap.io
      - MAIL_PORT=2525
      - MAIL_USERNAME=23bf9e27fd641e
      - MAIL_PASSWORD=3fad8e477b975f
      - MAIL_FROM_ADDRESS="ameya.sawant82@gmail.com"
      - MAIL_FROM_NAME="Ameya Sawant"
      - SCOUT_DRIVER=elasticsearch
    depends_on:
      - redis
      - db
      - elasticsearch
    volumes:
      - ./storage:/var/www/html/storage
      - ./bootstrap/cache:/var/www/html/bootstrap/cache
      - ./public:/var/www/html/public
    networks:
      - app_network
    entrypoint: ["/bin/sh", "-c", "
        php artisan config:cache &&
        php artisan route:cache &&
        php artisan view:cache &&
        php artisan storage:link &&
        php artisan migrate --force &&
        php artisan db:seed --force &&
        php-fpm
    "]

  queue:
    image: laravelblog:latest
    container_name: laravel_queue
    restart: unless-stopped
    depends_on:
      - redis
      - app
    command: php artisan queue:work --tries=3
    environment:
      - APP_ENV=production
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=ameya123
      - QUEUE_CONNECTION=redis
    networks:
      - app_network
    volumes:
      - ./storage:/var/www/html/storage
  
  scheduler:
    image: laravelblog:latest
    container_name: laravel_scheduler
    restart: unless-stopped
    working_dir: /var/www/html
    depends_on:
      - app
    command: ["sh", "-c", "while true; do php artisan schedule:run >> /dev/null 2>&1; sleep 60; done"]
    networks:
      - app_network

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=ameya123
      - MYSQL_DATABASE=laravel
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app_network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=ameya123
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - app_network

  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    command: redis-server --requirepass ameya123
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
  
volumes:
  dbdata:
    driver: local
  esdata:
    driver: local
  redisdata:
    driver: local
